### ISSUE TITLE
Notify the NPM folks that "peak NPM" has been achieved.

### ISSUE THREAD

**Issue by hacksalot** [sinclairzx81/zero#2]
Thanks. Amazing work, BTW. My favorite novelty app in forever.

https://www.reddit.com/r/programming/comments/djeycp/real_time_ascii_3d_renderer_for_nodejs_terminals/f46jxwb/

This is running perfectly on my 8-year-old Dell Latitude E6500 with 4GB RAM and Intel HD graphics and unremovable Windows Vista sticker attached via molecular annealing.

**Comment by sinclairzx81** [comment]
Haha, awesome, glad you like it :D
